services:
  postgres:
    image: postgres:15.4
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/prometheus
    command:
      - '--config.file=/prometheus/prometheus.yml'

  grafana:
    image: jennylember/jennylember-grafana-for-appliance-controller
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_DEFAULT_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_DEFAULT_PASSWORD}

  appliance-controller:
    build:
      context: ./
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres
      - pgadmin

volumes:
  postgres_data:
  pgadmin_data:
  grafana_data:
  prometheus_data:
