logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/db-changelog.xml

management:
  server:
    port: 8081
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    docExpansion: none
    operationsSorter: alpha
    tagsSorter: alpha


business-properties:
  programs:
    - id: 1
      deviceType: WASHING_MACHINE
      name: ECO 30
      prewashSupported: true
      quickSupported: false
      durationMs: 10000
    - id: 2
      deviceType: WASHING_MACHINE
      name: ECO 40
      prewashSupported: true
      quickSupported: false
      durationMs: 10000
    - id: 3
      deviceType: WASHING_MACHINE
      name: ECO 60
      prewashSupported: true
      quickSupported: false
      durationMs: 10000
    - id: 4
      deviceType: WASHING_MACHINE
      name: NORMAL 30
      prewashSupported: true
      quickSupported: false
      durationMs: 10000
    - id: 5
      deviceType: WASHING_MACHINE
      name: NORMAL 40
      prewashSupported: true
      quickSupported: false
      durationMs: 10000
    - id: 6
      deviceType: WASHING_MACHINE
      name: NORMAL 60
      prewashSupported: true
      quickSupported: false
      durationMs: 10000
    - id: 7
      deviceType: WASHING_MACHINE
      name: HAND WASH 40
      prewashSupported: true
      quickSupported: false
      durationMs: 10000
    - id: 8
      deviceType: WASHING_MACHINE
      name: FUR 30
      prewashSupported: true
      quickSupported: false
      durationMs: 10000

  modelToProgramsMapping:
    "Electrolux_SensiCare_800":
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8